name: Sycamore Consulting
markdown: redcarpet
pygments: true

source:		.
destination:	./_site
plugins:	./_plugins
layouts:	./_layouts
include:	[]
exclude:	[]
keep_files:	['.git']
gems:		[]
timezone:	nil
encoding:	UTF-8

url: http://www.sycamoreconsulting.co.uk

#gems:
#  - jekyll-redirect-from
# Google Tag Manager
google_tag_manager_id: GTM-KKX72Q